services:
  postgres:
    image: postgres:15
    container_name: csms_postgres
    environment:
      POSTGRES_USER: csms
      POSTGRES_PASSWORD: csms
      POSTGRES_DB: csms
      TZ: UTC
    ports:
      - "5433:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U csms -d csms || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped

  mariadb:
    image: mariadb:10.6
    container_name: csms_mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: steve
      MARIADB_USER: steve
      MARIADB_PASSWORD: steve
      TZ: UTC
    command:
      - mysqld
      - --default-time-zone=+00:00
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - ./.data/mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -usteve -p$MARIADB_PASSWORD -h 127.0.0.1 --silent"]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped

  steve:
    image: eclipse-temurin:17-jre
    container_name: csms_steve
    depends_on:
      mariadb:
        condition: service_healthy
    working_dir: /app
    volumes:
      - ./services/tools/steve:/app
      - ./.logs/steve:/app/logs
    command:
      - java
      - -Duser.home=/app
      - -DLOG_DIR=/app/logs
      - -Dlogback.configurationFile=/app/logback.xml
      - -Dspring.config.location=/app/steve.properties
      - -Dsteve.config=/app/steve.properties
      - -Dsteve.config.location=/app/steve.properties
      - -cp
      - steve.jar:lib/*
      - de.rwth.idsg.steve.Application
    environment:
      TZ: UTC
      STEVE_DB_URL: jdbc:mariadb://mariadb:3306/steve
      STEVE_DB_USER: steve
      STEVE_DB_PASS: steve
    ports:
      - "8180:8180"
    restart: unless-stopped

  orchestrator:
    image: node:20-alpine
    container_name: csms_orchestrator
    working_dir: /app
    # Monta o código-fonte, mas mantém node_modules dentro do container
    volumes:
      - ./services/orchestrator-api:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      TZ: UTC
      PORT: "3000"
      POSTGRES_URI: postgresql://csms:csms@postgres:5432/csms
      MARIADB_HOST: mariadb
      MARIADB_PORT: "3306"
      MARIADB_USER: steve
      MARIADB_PASSWORD: steve
      MARIADB_DATABASE: steve
      # opcional: CORS para front-ends locais
      CORS_ORIGIN: "http://localhost:8180,http://localhost:3000"
    command: >
      sh -lc "corepack enable &&
              corepack prepare pnpm@10.14.0 --activate &&
              pnpm install &&
              pnpm dev"
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/ready || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 20
    restart: unless-stopped
